#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 0.5; done

# launch first bar as main
# and all others as secondary
bar=primary

# launch the bars
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	MONITOR=$m polybar $bar &
	bar=secondary
  done
else
  polybar $bar &
fi
